#include "TicTac.h"

// default constructor
TicTac::TicTac(){

}

// deconstructor
TicTac::~TicTac(){

}

// sets Board to 0.0
char TicTac::SetBoard(){

	return '/';
}

// draws Board pretty print
void TicTac::Draw(){

}

// either 1 or 2 for input
void TicTac::Input(int){

}

// coin toss..may return an int
void TicTac::CoinToss(){


}

// toggles between X and O based on 1 and 0 generated by coin toss
void TicTac::TogglePlayer(int){


}

// did someone win? X or O?
char TicTac::Win(){
	return '/';
}

bool TicTac::BoardFull(){
	return true;
}

